"""empty message

Revision ID: 7aa92488ec6e
Revises: 2a3b1b0a2bbe
Create Date: 2024-04-08 10:40:56.661386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aa92488ec6e'
down_revision = '2a3b1b0a2bbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue_genre', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('venue_genre_artist_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Venue', ['venue_id'], ['id'])
        batch_op.drop_column('artist_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue_genre', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('venue_genre_artist_id_fkey', 'Artist', ['artist_id'], ['id'])
        batch_op.drop_column('venue_id')

    # ### end Alembic commands ###
